#!/usr/bin/env bash

# Author: Ibrahim Johar
# Description: Bookmark

readonly VERSION="0.4.0"
readonly DIR=~/.local/share/bookmark
readonly BOOKMARK=$DIR/bookmark
# $DMENU - Defined in ~/.profile
# $BROWSER - Defined in ~/.profile

main(){
    check_dir
    check_choice
    open_bm
}

check_dir(){
    if [[ ! -d $DIR ]]; then
        mkdir -p $DIR
    fi
}

prompt(){
    $DMENU -i -p $1
}

options(){
printf "Add\nDelete\n"
bm
}

bm(){
   cat $BOOKMARK | awk -F  " = "  '{print $1}'
}

choice(){
options | prompt "Bookmark"
}

add(){
    local url=$(prompt "Url")
    [[ -z $url ]] && exit
    local name=$(prompt "Name")

    echo "$name = $url" >> $BOOKMARK
}

delete(){
    local delete=$(bm | prompt "Delete")
    [[ -z $delete ]] && exit
    sed -i "/${delete} = /d" $BOOKMARK
}

selected_bm(){
    url=$(grep -w "$1 " $BOOKMARK | awk -F " = " '{print $2}')
}

check_choice(){
    local choice=$(choice)

    case $choice in
        Add)
            add
            ;;
        Delete)
            delete
            ;;
        *)
            [[ -z $choice ]] && exit
            selected_bm "$choice"
            ;;
    esac
}

open_bm(){
    [[ -z $url ]] && exit
    $BROWSER $url
}

main
