#!/usr/bin/env bash

# Author: Ibrahim Johar
# Description: Bookmark
# VERSION="0.2.1"

dir=~/.config/bookmark/list
bookmark=$(cat $dir)
button="Add\nDelete"

prompt(){
    rofi -i -dmenu $1
}

check_bookmark(){
    check=$(ls $dir | grep bookmark)

    if [[ -z $check ]]; then
        mkdir -p ~/.config/bookmark
        touch ~/.config/bookmark/list
    fi
}

check_bookmark

add_bookmark(){
    url=$(prompt)

    if [[ -z "$url" ]]; then
        exit
    else
        name_url=$(prompt)
    fi

    echo "$url = $name_url ;" >> $dir
}

newline(){
    echo $bookmark | sed 's/ ;/\n/g' | awk -F ' = ' '{print $2}'
}

list(){
    echo -e $button && newline | sed '/^$/d'
}

del_bookmark(){
    del=$(newline | sed '/^$/d' | prompt)
    cat $dir | sed -i "/$del/d" $dir
}

begin=$(list | prompt -no-custom)

if [[ -z $begin ]]; then
    exit
elif [ "$begin" = "Add" ]; then
    add_bookmark
elif [ "$begin" = "Delete" ]; then
    del_bookmark
else
    open_url=$(cat $dir | grep "$begin" | awk -F ' = ' '{print $1}')
    $BROWSER $open_url
fi

