#!/usr/bin/env bash

# Author: Ibrahim Johar
# Version: 0.3.0
# Description: Print current mpd playing song in dwmblocks

# Blue color for dwmblocks
bg0=^b#314f57^

off="volume: n/a   repeat: off   random: off   single: off   consume: off"
duration=$(mpc | awk 'NR==2 {print $3}')

song() {
	mpc current
}

hipen() {
	song |
		sed 's/ /\n/g' |
		grep "-"
}

check_state() {
	mpc | awk 'NR==2 {print $1}'
}

song_name() {
	song | awk -F ' - ' '{print $2}'
}

trunckad() {
	song_name |
		sed 's/ /\n/g' |
		sed -n '1, 4'p |
		sed 's/$/ /' |
		tr -d '\n' |
		sed 's/ $//'
}

get_line_count() {
	song_name |
		sed 's/ /\n/g' |
		wc -l
}

state() {
	if [ "$(check_state)" == "[paused]" ]; then
		echo "${bg0}  $($1) "
	elif [ "$(check_state)" == "[playing]" ]; then
		if (($(get_line_count) > 4)); then
			echo "${bg0}  $($1)... [$duration] "
		else
			echo "${bg0}  $($1) [$duration] "
		fi
	fi
}

check_hipen() {
	if [[ $(hipen) = "-" ]]; then
		state trunckad
	else
		state song
	fi
}

if [ "$song" == "$off" ]; then
	echo ""
else
	check_hipen
fi
