#!/usr/bin/env bash
# Author: Ibrahim Johar
# Date: 2024-01-05
# Description: Screenshot tool that use maim
# Version: 0.0.2

readonly DIR="$HOME/Pictures/screenshot"
readonly TODAY=$(date +%Y-%m-%d)

[[ -z $DMENU ]] && DMENU="rofi -dmenu"

check_dep(){
    local dep=1
    if [[ $XDG_SESSION_TYPE == "wayland" ]]; then
        [[ -z $(command -v slurp) ]] && echo "slurp is not installed" && dep=0
        [[ -z $(command -v grim) ]] && echo "grim is not installed" && dep=0
    elif [[ $XDG_SESSION_TYPE == "x11" ]]; then
        [[ -z $(command -v maim) ]] && echo "maim is not installed" && dep=0
        [[ -z $(command -v xclip) ]] && echo "xclip is not installed" && dep=0
    fi

    [[ $dep == 0 ]] && exit
}

check_dir(){
    [[ ! -d $DIR ]] && mkdir -p $DIR
}


select_menu(){
    printf "Select\nScreen" | $DMENU
}

screenshot(){
    local selected=$(select_menu)
    local num=$(( $(find $DIR -maxdepth 1 -name "$TODAY*" | wc -l) + 1 ))

    if [[ $XDG_SESSION_TYPE == "wayland" ]]; then
        if [[ $selected = "Select" ]]; then
            local dim=$(slurp)
            grim -g "$dim" - | tee "$DIR"/"$TODAY"_"$num".png | wl-copy
            notify-send "${TODAY}_${num}.png" -i "$DIR"/"$TODAY"_"$num".png
        elif [[ $selected = "Screen" ]]; then
            grim - | tee "$DIR"/"$TODAY"_"$num".png | wl-copy
            notify-send "${TODAY}_${num}.png" -i "$DIR"/"$TODAY"_"$num".png
        fi
    elif [[ $XDG_SESSION_TYPE == "x11" ]]; then
        if [[ $selected = "Select" ]]; then
            maim -s -m 10 | tee "$DIR"/"$TODAY"_"$num".jpg | xclip -selection clipboard -t image/png
            notify-send "${TODAY}_${num}.png" -i "$DIR"/"$TODAY"_"$num".png
        elif [[ $selected = "Screen" ]]; then
            maim -m 10 | tee "$DIR"/"$TODAY"_"$num".jpg | xclip -selection clipboard -t image/png
            notify-send "${TODAY}_${num}.png" -i "$DIR"/"$TODAY"_"$num".png
        fi
    fi
}

check_dep
check_dir
screenshot
